apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: test
  name: test
spec:
  replicas: 10
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - image: httpd
          name: httpd
          command: ["/bin/bash", "-c"] # override the default command to induce an error
          args: ["sleep 5; exit 1"] # sleep for 5 seconds and then exit with error code 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
status: {}
