apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mealie
  name: mealie
  namespace: mealie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mealie
  template:
    metadata:
      labels:
        app: mealie
    spec:
      containers:
        - image: ghcr.io/mealie-recipes/mealie:v3.3.2
          name: mealie-recipes
          ports:
            - containerPort: 9000 # from docs - https://mealie.io/docs/installation/docker - port for the pod connection
          volumeMounts:
            - mountPath: /app/data # mount path for mealie data
              name: mealie-data
      volumes:
        - name: mealie-data
          persistentVolumeClaim:
            claimName: mealie-data
