service:
  main:
    ports:
      http:
        port: 7575
        targetPort: 3000

probes:
  liveness:
    enabled: true
    custom: true
    spec:
      httpGet:
        path: /api/health/live
        port: 3000
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3

  readiness:
    enabled: true
    custom: true
    spec:
      httpGet:
        path: /api/health/ready
        port: 3000
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
